import unittest
from animeflv.db.mongo import Mongo

class TestDB(unittest.TestCase):
    def test_mongo(self):
        mongo = Mongo()

        data = [{'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2670.jpg',
        'title': 'ChäoS;Child',
        'url': 'http://animeflv.net/ver/44510/chaos-child-11'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2671.jpg',
        'title': 'Kobayashi-san Chi no Maid Dragon',
        'url': 'http://animeflv.net/ver/44509/kobayashi-san-chi-no-maid-dragon-11'},
       {'episode': 12,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2641.jpg',
        'title': "Akiba's Trip The Animation",
        'url': 'http://animeflv.net/ver/44508/akibas-trip-the-animation-12'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2669.jpg',
        'title': 'One Room',
        'url': 'http://animeflv.net/ver/44507/one-room-11'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2668.jpg',
        'title': 'Piace: Watashi no Italian',
        'url': 'http://animeflv.net/ver/44506/piace-watashi-no-italian-11'},
       {'episode': 49,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2441.jpg',
        'title': 'Sousei no Onmyouji',
        'url': 'http://animeflv.net/ver/44505/sousei-no-onmyouji-49'},
       {'episode': 25,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2573.jpg',
        'title': 'Nanbaka',
        'url': 'http://animeflv.net/ver/44504/nanbaka-25'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2667.jpg',
        'title': 'Kemono Friends',
        'url': 'http://animeflv.net/ver/44503/kemono-friends-11'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2666.jpg',
        'title': 'Hand Shakers',
        'url': 'http://animeflv.net/ver/44502/hand-shakers-11'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2664.jpg',
        'title': 'Onihei',
        'url': 'http://animeflv.net/ver/44501/onihei-11'},
       {'episode': 12,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2640.jpg',
        'title': 'Ai Mai Mii: Surgical Friends',
        'url': 'http://animeflv.net/ver/44500/ai-mai-mii-surgical-friends-12'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2665.jpg',
        'title': 'ACCA: 13-ku Kansatsu-ka',
        'url': 'http://animeflv.net/ver/44499/acca-13-ku-kansatsu-ka-11'},
       {'episode': 25,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2574.jpg',
        'title': 'Nobunaga no Shinobi',
        'url': 'http://animeflv.net/ver/44498/nobunaga-no-shinobi-25'},
       {'episode': 24,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2609.jpg',
        'title': 'Digimon Universe: Appli Monsters',
        'url': 'http://animeflv.net/ver/44497/digimon-universe-appli-monsters-24'},
       {'episode': 23,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2569.jpg',
        'title': 'Trickster: Edogawa Ranpo "Shounen Tanteidan" yori',
        'url': 'http://animeflv.net/ver/44496/trickster-edogawa-ranpo-shounen-tanteidan-yori-23'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2663.jpg',
        'title': 'Yowamushi Pedal: New Generation',
        'url': 'http://animeflv.net/ver/44495/yowamushi-pedal-new-generation-11'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2662.jpg',
        'title': 'Chiruran: Nibun no Ichi',
        'url': 'http://animeflv.net/ver/44494/chiruran-nibun-no-ichi-11'},
       {'episode': 147,
        'image': 'http://animeflv.net/uploads/animes/thumbs/1288.jpg',
        'title': 'Yu-Gi-Oh: Arc-V',
        'url': 'http://animeflv.net/ver/44493/yu-gi-oh-arc-v-147'},
       {'episode': 11,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2661.jpg',
        'title': 'Gabriel DropOut',
        'url': 'http://animeflv.net/ver/44492/gabriel-dropout-11'},
       {'episode': 6,
        'image': 'http://animeflv.net/uploads/animes/thumbs/2610.jpg',
        'title': 'Masou Gakuen HxH Special',
        'url': 'http://animeflv.net/ver/44491/masou-gakuen-hxh-special-6'}]

        res = mongo.new_episodes(data=data, action="WRITE")
        self.assertTrue(res)
        res = mongo.new_episodes(flush=True)
        self.assertTrue(res)

if __name__ == '__main__':
    unittest.main()